name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: build
        run: pip install -r dev_requirements.txt
      - name: tests
        run: pytest --cov .
